project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/togogh
      - icon: linkedin
        href: https://www.linkedin.com/in/ysabelcaballes/
format:
  html:
    theme: cyborg
    css: styles.css



